environment-type = "development"
keystore-path = "/Users/brett/Library/Ethereum/keystore"
keystore-file-path = "/Users/brett/Library/Ethereum/keystore/UTC--2020-06-27T10-53-01Z--8dd3061b-9f22-4205-9c64-fb4601fca5c8"
address = "0x74d6aC01f1423dd8Ef62760Ba4EC8ADF9B584F38"
password-file = "/Users/brett/.local/share/raiden/0x74d6aC01f1423dd8Ef62760Ba4EC8ADF9B584F38.passphrase.txt"
user-deposit-contract-address = "0x0794F09913AA8C77C8c5bdd1Ec4Bb51759Ee0cC5"
network-id = "goerli"
accept-disclaimer = true
#eth-rpc-endpoint = "https://goerli.infura.io:443/v3/44e91c40827a4a7081e22c55b4a2ae50"
eth-rpc-endpoint = "http://localhost:8545"
routing-mode = "pfs"
enable-monitoring = true
#pathfinding-service-address = "https://pfs-goerli.services-dev.raiden.network"
pathfinding-service-address = "https://pfs-goerli-with-fee.services-dev.raiden.network"
api-address = "localhost:5004"

