version: '3.4'

x-raiden: &raiden
    image: raidennetwork/raiden:v1.1.0
    network_mode: "host"
    depends_on:
      - geth
    command:
      --keystore-path /shared/keystore
      --environment-type development
      --network-id goerli
      --accept-disclaimer
      --datadir /shared
      --enable-monitoring
      --eth-rpc-endpoint http://${GETH_IP_ADDR}:${GETH_RPC_PORT}

services:

  geth:
    image: ethereum/client-go:v1.9.15
    network_mode: "host"
    volumes:
      - ./volumes/geth_persistent_blockchain:/shared
    ports:
      - 30303:30303
      - 8545:${GETH_RPC_PORT}
    # XXX: This is a workaround for #23.
    restart: on-failure
    command:
      --goerli
      --http
      --http.addr "0.0.0.0"
      --nousb
      --datadir /shared
      --ipcpath /root/.ethereum/geth.ipc

  raiden1:
    <<: *raiden
    ports:
      - 5001:${RAIDEN_API_PORT}
    volumes:
      - './volumes/raiden1:/shared'

  raiden2:
    <<: *raiden
    ports:
      - 5002:${RAIDEN_API_PORT}
    volumes:
      - './volumes/raiden2:/shared'

  raiden3:
    <<: *raiden
    ports:
      - 5003:${RAIDEN_API_PORT}
    volumes:
      - './volumes/raiden3:/shared'
