address = "0x1159915CFd2E19223edb08B0CD6711EAC0fA87a6"
password-file = "/shared/passphrases/1159915cfd2e19223edb08b0cd6711eac0fa87a6.passphrase.txt"
pathfinding-service-address = "https://pfs-goerli-with-fee.services-dev.raiden.network"
