environment-type = "development"
keystore-path = "/shared/keystore"
keystore-file-path = "/shared/keystore/UTC--2020-05-25T08-54-21Z--5ba39cb6-fc76-42ad-b864-b4709e5021b0"
address = "0x961D954009Db8D9ab527632D7537411f3b3b8473"
password-file = "/shared/passphrases/961d954009db8d9ab527632d7537411f3b3b8473.passphrase.txt"
user-deposit-contract-address = "0x0794F09913AA8C77C8c5bdd1Ec4Bb51759Ee0cC5"
network-id = "goerli"
accept-disclaimer = true
routing-mode = "pfs"
enable-monitoring = "True"
pathfinding-service-address = "https://pfs-goerli-with-fee.services-dev.raiden.network"
api-address = "localhost:5003"
