address = "0x74d6aC01f1423dd8Ef62760Ba4EC8ADF9B584F38"
password-file = "/shared/passphrases/0x74d6aC01f1423dd8Ef62760Ba4EC8ADF9B584F38.passphrase.txt"
pathfinding-service-address = "https://pfs-goerli-with-fee.services-dev.raiden.network"

user-deposit-contract-address = "0x0794F09913AA8C77C8c5bdd1Ec4Bb51759Ee0cC5"
#eth-rpc-endpoint = "https://goerli.infura.io:443/v3/44e91c40827a4a7081e22c55b4a2ae50"
routing-mode = "pfs"
enable-monitoring = true
#pathfinding-service-address = "https://pfs-goerli.services-dev.raiden.network"
